version: '3.1'

services:

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: resep

    ports:
      - 5432:5432

  adminer:
    image: adminer:4
    restart: always
    ports:
      - 8080:8080